---
- name: configure tower
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - awx.awxi
  pre_tasks:
    - name: getting UID
      shell: "hostname | cut -d '.' -f 2"
      register: uid

    - name: updating variable
      inlinefile:
        path: ~/ansible_advanced_tower_conf/roles/tower_config/defaults/main.yml
        regexp: '^tower_hostname:'
        line: "tower_hostname: https://tower1.{{ uid.stdout }}.example.opentlc.com"

  roles:
    - tower_config
