---
- name: configure tower
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  collections:
    - awx.awx
  pre_tasks:
    - name: getting GUID
      shell: "hostname | cut -d '.' -f 2"
      register: r_guid
      tags:
        - always

    - name: updating variable
      set_fact:
        tower_hostname: "https://tower1.{{ r_guid.stdout }}.example.opentlc.com"
      tags:
        - always
        
  roles:
    - tower_config
