---
- name: Add tower inventory
  awx.awx.tower_inventory:
    name: "{{ __tower_inventory.name }}"
    description: "{{ __tower_inventory.description  }}"
    organization: "{{ __tower_inventory.organization | default('gpte') }}"
    state: "{{ __tower_inventory.state | default('present') }}"
    tower_host: "{{ tower_hostname }}"
    tower_username: "{{ tower_admin_username | default('admin') }}"
    tower_password: "{{ tower_admin_password }}"
    tower_verify_ssl: "{{ tower_verify_ssl | default(false) }}"
  loop: "{{ tower_inventories }}"
  loop_control:
    loop_var: __tower_inventory
