---
- name: Add Ansible Tower Job Template
  awx.awx.tower_job_template:
    name: "{{ __tower_job_template.name }}"
    description: "{{ __tower_job_template.description }}"
    job_type: "{{ __tower_job_template.job_type | default('run') }}"
    inventory: "{{ __tower_job_template.inventory | default(omit) }}"
    vault_credential: "{{ __tower_job_template.vault_credential | default(omit) }}"
    credential: "{{ __tower_job_template.credential | default(omit) }}"
    ask_extra_vars: "{{ __tower_job_template.ask_extra_vars | default(omit) }}"
    project: "{{ __tower_job_template.project }}"
    playbook: "{{ __tower_job_template.playbook | default('main.yml') }}"
    become_enabled: "{{ __tower_job_template.become | default('no') }}"
    concurrent_jobs_enabled: "{{ __tower_job_template.concurrent_jobs_enabled | default('yes') }}"
    state: "{{ __tower_job_template.state | default('present') }}"
    tower_host: "{{ tower_hostname }}"
    tower_username: "{{ tower_admin_username | default('admin') }}"
    tower_password: "{{ tower_admin_password }}"
    tower_verify_ssl: "{{ tower_verify_ssl | default(false) }}"
    verbosity: "{{ __tower_job_template.verbosity | default(0) }}"
    forks: "{{ __tower_job_template.forks | default(1) }}"
  loop: "{{ tower_job_templates }}"
  loop_control:
    loop_var: __tower_job_template
