
---
- name: Add tower credentials for Satellite
  awx.awx.tower_credential:
    name: "{{ __tower_credential.name }}"
    inputs:
      username: "{{ __tower_credential.username }}"
      password: "{{ __tower_credential.password | default(omit) }}"
      ssh_key_data: "{{ __tower_credential.ssh_key_data | default(omit) }}"
      host: "{{ __tower_credential.host | default(omit) }}"
      become_method: "{{ __tower_credential.become_method | default(omit) }}"
    description: "{{ __tower_credential.description | default(omit) }}"
    organization: "{{ __tower_credential.organization | default('Default') }}"
    credential_type: "{{ __tower_credential.type }}"
    state: "{{ __tower_credential.state | default('present') }}"
    tower_host: "{{ tower_hostname }}"
    tower_username: "{{ tower_admin_username | default('admin') }}"
    tower_password: "{{ tower_admin_password }}"
    tower_verify_ssl: "{{ tower_verify_ssl | default('false') }}"
  loop: "{{ tower_credentials }}"
  loop_control:
    loop_var: __tower_credential
