---
- name: Create tower project(s)
  awx.awx.tower_project:
    name: "{{ __tower_project.name }}"
    description: "{{ __tower_project.description }}"
    organization: "{{ __tower_project.organization | default('Default') }}"
    scm_url: "{{ __tower_project.scm_url | default(omit)}}"
    scm_type: "{{ __tower_project.scm_type | default('git') }}"
    scm_credential: "{{ __tower_project.scm_credential | default(omit)}}"
    scm_branch: "{{ __tower_project.scm_branch | default('master') }}"
    scm_update_on_launch: "{{ __tower_project.scm_update_on_launch | default('false') }}"
    state: "{{ __tower_project.state | default('present') }}"
    tower_host: "{{ tower_hostname }}"
    tower_username: "{{ tower_admin_username | default('admin') }}"
    tower_password: "{{ tower_admin_password }}"
    tower_verify_ssl: "{{ tower_verify_ssl | default(false) }}"
  loop: "{{ tower_projects }}"
  loop_control:
    loop_var: __tower_project

- name: Sleep to allow tower projects to update
  wait_for:
    timeout: 60
