---
- name: Add tower inventory source
  awx.awx.tower_inventory_source:
    name: "{{ __tower_inventory_source.name }}"
    description: "{{ __tower_inventory_source.description }}"
    inventory: "{{ __tower_inventory_source.inventory }}"
    credential: "{{ __tower_inventory_source.credential | default(omit) }}"
    source: "{{ __tower_inventory_source.source }}"
    source_project: "{{ __tower_inventory_source.source_project | default(omit) }}"
    source_path: "{{ __tower_inventory_source.source_path | default(omit) }}"
    state: "{{ __tower_inventory_source.state | default('present') }}"
    update_on_launch: "{{ __tower_inventory_source.update_on_launch | default(true) }}"
    tower_host: "{{ tower_hostname }}"
    tower_username: "{{ tower_admin_username | default('admin') }}"
    tower_password: "{{ tower_admin_password }}"
    tower_verify_ssl: "{{ tower_verify_ssl | default(false) }}"
  loop: "{{ tower_inventory_source }}"
  loop_control:
    loop_var: __tower_inventory_source
